name: 'lint'

on:
  push:

jobs:
  lint:
    name: 'Running linting'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install pycodestyle
        pip install pylint
    - name: Lint
      run: |
        bash lint.sh
